/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.time.LocalDateTime;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

        LocalDateTime of = LocalDateTime.of(1990, 1, 32, 0, 0, 0, 0);

        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
