### profile name
spring:
  profiles:
    active: dev

---
spring:
  config:
    activate.on-profile: dev
    import: optional:classpath:dev.yml
#   import: optional:file:./config/dev.yml


---
spring:
  config:
    activate.on-profile: prod



