#### Spring Config
# =============================================================================
## Session
# =============================================================================
#server.session.persistent=true

# =============================================================================
## View Path resources/WEB-INF/jsp/*.jsp
# =============================================================================
#spring.mvc.view.prefix = WEB-INF/jsp/
#spring.mvc.view.suffix = .jsp
#spring.mvc.static-path-pattern=/resources/**


# =============================================================================
## ETC
# =============================================================================
spring:
  main.allow-bean-definition-overriding: true
  main.banner-mode: off
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080






# Built-in log
logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.web.filter: debug







# =============================================================================
## Data DB
# =============================================================================
database:
  url: jdbc:mysql://192.168.1.4:3306/fivetek?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
  driverClassName: com.mysql.cj.jdbc.Driver
  username: shh
  password: shh




# =============================================================================
## DBCP Config
# =============================================================================
dbcp:
  poolInitialSize: 1
  poolMaxSize: 3
  connectionTimeoutInMs: 4000
  connectionIdleLimitInSeconds: 10
  logQueryExecutionLongerThanMs: 500
  logStackTraceForLongQueryExecution: true
  statementCacheMaxSize: 200
  validationQuery: select 1
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 30000



# =============================================================================
## Hibernate Config
# =============================================================================
jpa:
  hibernate.hbm2ddl.auto: none
  hibernate.show_sql: false
  hibernate.dialect:  org.fivetek.db.MysqlExtendDialect
  hibernate.jdbc.time_zone: Asia/Seoul
  show_sql: false
  format_sql: false
  use_sql_commnets: true

