/* 1번째 db */

CREATE DATABASE shhdb1;

CREATE TABLE shhdb1.TEST01 (
	id BIGINT auto_increment NOT NULL,
	username VARCHAR(100) NULL,
	CONSTRAINT TEST01_PK PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO shhdb1.TEST01 (username)
	VALUES ('홍길동');



/* 2번째 db */

CREATE DATABASE shhdb2;


CREATE TABLE shhdb2.TEST01 (
	id BIGINT auto_increment NOT NULL,
	username VARCHAR(100) NULL,
	CONSTRAINT TEST01_PK PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO shhdb1.TEST01 (username)
	VALUES ('이순신');


