spring:
  profiles:
    active: dev
---

spring:
  config:
    activate:
      on-profile: dev
    main.allow-bean-definition-overriding: true
    main.banner-mode: off
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
server:
  port: 30090
